### USERS
GET http://localhost:3000/users
###
GET http://localhost:3000/users/1
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname": "boii",
    "lastname": "BAW",
    "email": "test@test.fr",
    "password": "Azerty1234!"
}
###
GET http://localhost:3000/users/1684924289588
###
PUT http://localhost:3000/users/2
Content-Type: application/json

{
    "firstname": "John Doe",
    "email": "t2@t.com",
    "password": "Azerty1234!"
}
###
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
    "password": "Azerty1234!"
}
###
PATCH http://localhost:3000/users/234256789
Content-Type: application/json

{
    "name": "Jane Doe"
}
###
DELETE http://localhost:3000/users/2

### SECURITY
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "t3@t.com",
    "password": "Azerty1234!"
}